# Shared HTTP entry (created once by global provisioning)
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    client_max_body_size 2g;
    access_log /var/log/nginx/cloudteor-access.log;
    error_log  /var/log/nginx/cloudteor-error.log;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    include /etc/nginx/cloudteor-apps/*.conf;
}
